name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BDSX_YES: skip

    steps:
      - uses: actions/checkout@v2

      - name: NPM Install
        run: npm i

      - name: TypeScript Check
        run: |
          npm list --depth=0 typescript
          tsc --noEmit

      - name: ESLint
        run: |
          npm list --depth=0 eslint eslint-plugin-github eslint-plugin-import
          npm run lint-bdsx
