// this is imported from ../index.ts
// Console Output
console.log("[example/index] Hello, BDSX!");

import "./actor-effects";
import "./attribute";
import "./blockcustomname";
import "./customcommand";
import "./custommotd";
import "./event-blockdestroy";
import "./event-knockback";
import "./event-playerdropitem";
import "./executecommand";
import "./form";
import "./hidemapmarker";
import "./inventory";
import "./ipban";
import "./lowlevel-apihooking";
import "./lowlevel-asm";
import "./lowlevel-dll";
import "./lowlevel-nativeclass";
import "./lowlevel-string-and-vector";
import "./nbt-sign";
import "./net-chat";
import "./net-disconnect";
import "./net-login";
import "./net-ping";
import "./net-printall";
import "./net-rawpacket";
import "./net-scorepacket";
import "./net-sendhook";
import "./net-transferserver";
import "./setblock";
import "./settitle";
import "./simulatedplayer";
import "./storage";
import "./test";
import "./vulnerabilities";
import "./shoot-projectile";
// import './permissions';
