export declare enum SymTagEnum {
    SymTagNull = 0,
    SymTagExe = 1,
    SymTagCompiland = 2,
    SymTagCompilandDetails = 3,
    SymTagCompilandEnv = 4,
    SymTagFunction = 5,
    SymTagBlock = 6,
    SymTagData = 7,
    SymTagAnnotation = 8,
    SymTagLabel = 9,
    SymTagPublicSymbol = 10,
    SymTagUDT = 11,
    SymTagEnum = 12,
    SymTagFunctionType = 13,
    SymTagPointerType = 14,
    SymTagArrayType = 15,
    SymTagBaseType = 16,
    SymTagTypedef = 17,
    SymTagBaseClass = 18,
    SymTagFriend = 19,
    SymTagFunctionArgType = 20,
    SymTagFuncDebugStart = 21,
    SymTagFuncDebugEnd = 22,
    SymTagUsingNamespace = 23,
    SymTagVTableShape = 24,
    SymTagVTable = 25,
    SymTagCustom = 26,
    SymTagThunk = 27,
    SymTagCustomType = 28,
    SymTagManagedType = 29,
    SymTagDimension = 30,
    SymTagCallSite = 31,
    SymTagInlineSite = 32,
    SymTagBaseInterface = 33,
    SymTagVectorType = 34,
    SymTagMatrixType = 35,
    SymTagHLSLType = 36,
    SymTagCaller = 37,
    SymTagCallee = 38,
    SymTagExport = 39,
    SymTagHeapAllocationSite = 40,
    SymTagCoffGroup = 41,
    SymTagMax = 42
}
export declare const SYMFLAG_VALUEPRESENT = 1;
export declare const SYMFLAG_REGISTER = 8;
export declare const SYMFLAG_REGREL = 16;
export declare const SYMFLAG_FRAMEREL = 32;
export declare const SYMFLAG_PARAMETER = 64;
export declare const SYMFLAG_LOCAL = 128;
export declare const SYMFLAG_CONSTANT = 256;
export declare const SYMFLAG_EXPORT = 512;
export declare const SYMFLAG_FORWARDER = 1024;
export declare const SYMFLAG_FUNCTION = 2048;
export declare const SYMFLAG_VIRTUAL = 4096;
export declare const SYMFLAG_THUNK = 8192;
export declare const SYMFLAG_TLSREL = 16384;
export declare const SYMFLAG_SLOT = 32768;
export declare const SYMFLAG_ILREL = 65536;
export declare const SYMFLAG_METADATA = 131072;
export declare const SYMFLAG_CLR_TOKEN = 262144;
export declare const SYMFLAG_NULL = 524288;
export declare const SYMFLAG_FUNC_NO_RETURN = 1048576;
export declare const SYMFLAG_SYNTHETIC_ZEROBASE = 2097152;
export declare const SYMFLAG_PUBLIC_CODE = 4194304;
export declare const SYMOPT_CASE_INSENSITIVE = 1;
export declare const SYMOPT_UNDNAME = 2;
export declare const SYMOPT_DEFERRED_LOADS = 4;
export declare const SYMOPT_NO_CPP = 8;
export declare const SYMOPT_LOAD_LINES = 16;
export declare const SYMOPT_OMAP_FIND_NEAREST = 32;
export declare const SYMOPT_LOAD_ANYTHING = 64;
export declare const SYMOPT_IGNORE_CVREC = 128;
export declare const SYMOPT_NO_UNQUALIFIED_LOADS = 256;
export declare const SYMOPT_FAIL_CRITICAL_ERRORS = 512;
export declare const SYMOPT_EXACT_SYMBOLS = 1024;
export declare const SYMOPT_ALLOW_ABSOLUTE_SYMBOLS = 2048;
export declare const SYMOPT_IGNORE_NT_SYMPATH = 4096;
export declare const SYMOPT_INCLUDE_32BIT_MODULES = 8192;
export declare const SYMOPT_PUBLICS_ONLY = 16384;
export declare const SYMOPT_NO_PUBLICS = 32768;
export declare const SYMOPT_AUTO_PUBLICS = 65536;
export declare const SYMOPT_NO_IMAGE_SEARCH = 131072;
export declare const SYMOPT_SECURE = 262144;
export declare const SYMOPT_NO_PROMPTS = 524288;
export declare const SYMOPT_OVERWRITE = 1048576;
export declare const SYMOPT_IGNORE_IMAGEDIR = 2097152;
export declare const SYMOPT_FLAT_DIRECTORY = 4194304;
export declare const SYMOPT_FAVOR_COMPRESSED = 8388608;
export declare const SYMOPT_ALLOW_ZERO_ADDRESS = 16777216;
export declare const SYMOPT_DISABLE_SYMSRV_AUTODETECT = 33554432;
export declare const SYMOPT_READONLY_CACHE = 67108864;
export declare const SYMOPT_SYMPATH_LAST = 134217728;
export declare const SYMOPT_DISABLE_FAST_SYMBOLS = 268435456;
export declare const SYMOPT_DISABLE_SYMSRV_TIMEOUT = 536870912;
export declare const SYMOPT_DISABLE_SRVSTAR_ON_STARTUP = 1073741824;
export declare const SYMOPT_DEBUG = 2147483648;
export declare const UNDNAME_COMPLETE = 0;
export declare const UNDNAME_NO_LEADING_UNDERSCORES = 1;
export declare const UNDNAME_NO_MS_KEYWORDS = 2;
export declare const UNDNAME_NO_FUNCTION_RETURNS = 4;
export declare const UNDNAME_NO_ALLOCATION_MODEL = 8;
export declare const UNDNAME_NO_ALLOCATION_LANGUAGE = 16;
export declare const UNDNAME_NO_MS_THISTYPE = 32;
export declare const UNDNAME_NO_CV_THISTYPE = 64;
export declare const UNDNAME_NO_THISTYPE = 96;
export declare const UNDNAME_NO_ACCESS_SPECIFIERS = 128;
export declare const UNDNAME_NO_THROW_SIGNATURES = 256;
export declare const UNDNAME_NO_MEMBER_TYPE = 512;
export declare const UNDNAME_NO_RETURN_UDT_MODEL = 1024;
export declare const UNDNAME_32_BIT_DECODE = 2048;
export declare const UNDNAME_NAME_ONLY = 4096;
export declare const UNDNAME_NO_ARGUMENTS = 8192;
export declare const UNDNAME_NO_SPECIAL_SYMS = 16384;
