import { VoidPointer } from "./core";
import { NativeArray, NativeClass } from "./nativeclass";
import { bin64_t, int32_t, uint16_t, uint32_t, uint8_t } from "./nativetype";
export declare const MAX_PATH = 260;
export declare const PAGE_NOACCESS = 1;
export declare const PAGE_READONLY = 2;
export declare const PAGE_READWRITE = 4;
export declare const PAGE_WRITECOPY = 8;
export declare const PAGE_EXECUTE = 16;
export declare const PAGE_EXECUTE_READ = 32;
export declare const PAGE_EXECUTE_READWRITE = 64;
export declare const PAGE_EXECUTE_WRITECOPY = 128;
export declare const PAGE_GUARD = 256;
export declare const PAGE_NOCACHE = 512;
export declare const PAGE_WRITECOMBINE = 1024;
export declare const PAGE_GRAPHICS_NOACCESS = 2048;
export declare const PAGE_GRAPHICS_READONLY = 4096;
export declare const PAGE_GRAPHICS_READWRITE = 8192;
export declare const PAGE_GRAPHICS_EXECUTE = 16384;
export declare const PAGE_GRAPHICS_EXECUTE_READ = 32768;
export declare const PAGE_GRAPHICS_EXECUTE_READWRITE = 65536;
export declare const PAGE_GRAPHICS_COHERENT = 131072;
export declare const PAGE_ENCLAVE_THREAD_CONTROL = 2147483648;
export declare const PAGE_REVERT_TO_FILE_MAP = 2147483648;
export declare const PAGE_TARGETS_NO_UPDATE = 1073741824;
export declare const PAGE_TARGETS_INVALID = 1073741824;
export declare const PAGE_ENCLAVE_UNVALIDATED = 536870912;
export declare const PAGE_ENCLAVE_DECOMMIT = 268435456;
export declare const MEM_COMMIT = 4096;
export declare const MEM_RESERVE = 8192;
export declare const MEM_REPLACE_PLACEHOLDER = 16384;
export declare const MEM_RESERVE_PLACEHOLDER = 262144;
export declare const MEM_RESET = 524288;
export declare const MEM_TOP_DOWN = 1048576;
export declare const MEM_WRITE_WATCH = 2097152;
export declare const MEM_PHYSICAL = 4194304;
export declare const MEM_ROTATE = 8388608;
export declare const MEM_DIFFERENT_IMAGE_BASE_OK = 8388608;
export declare const MEM_RESET_UNDO = 16777216;
export declare const MEM_LARGE_PAGES = 536870912;
export declare const MEM_4MB_PAGES = 2147483648;
export declare const MEM_64K_PAGES: number;
export declare const MEM_UNMAP_WITH_TRANSIENT_BOOST = 1;
export declare const MEM_COALESCE_PLACEHOLDERS = 1;
export declare const MEM_PRESERVE_PLACEHOLDER = 2;
export declare const MEM_DECOMMIT = 16384;
export declare const MEM_RELEASE = 32768;
export declare const MEM_FREE = 65536;
export declare const CHAR: import("./nativetype").NativeType<number, number>;
export declare type CHAR = uint8_t;
export declare const BYTE: import("./nativetype").NativeType<number, number>;
export declare type BYTE = uint8_t;
export declare const WORD: import("./nativetype").NativeType<number, number>;
export declare type WORD = uint16_t;
export declare const DWORD: import("./nativetype").NativeType<number, number>;
export declare type DWORD = uint32_t;
export declare const LONG: import("./nativetype").NativeType<number, number>;
export declare type LONG = int32_t;
export declare const ULONGLONG: import("./nativetype").NativeType<string, string> & {
    one: string;
    zero: string;
    minus_one: string;
};
export declare type ULONGLONG = bin64_t;
export declare const ULONG_PTR: import("./nativetype").NativeType<string, string> & {
    one: string;
    zero: string;
    minus_one: string;
};
export declare type ULONG_PTR = bin64_t;
export declare const IMAGE_NUMBEROF_DIRECTORY_ENTRIES = 16;
export declare const IMAGE_DOS_SIGNATURE = 23117;
export declare const IMAGE_DIRECTORY_ENTRY_EXPORT = 0;
export declare const IMAGE_DIRECTORY_ENTRY_IMPORT = 1;
export declare const IMAGE_DIRECTORY_ENTRY_RESOURCE = 2;
export declare const IMAGE_DIRECTORY_ENTRY_EXCEPTION = 3;
export declare const IMAGE_DIRECTORY_ENTRY_SECURITY = 4;
export declare const IMAGE_DIRECTORY_ENTRY_BASERELOC = 5;
export declare const IMAGE_DIRECTORY_ENTRY_DEBUG = 6;
export declare const IMAGE_DIRECTORY_ENTRY_ARCHITECTURE = 7;
export declare const IMAGE_DIRECTORY_ENTRY_GLOBALPTR = 8;
export declare const IMAGE_DIRECTORY_ENTRY_TLS = 9;
export declare const IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG = 10;
export declare const IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT = 11;
export declare const IMAGE_DIRECTORY_ENTRY_IAT = 12;
export declare const IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT = 13;
export declare const IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR = 14;
export declare const IMAGE_ORDINAL_FLAG64: string;
export declare const IMAGE_ORDINAL_FLAG32 = 2147483648;
export declare const b64_LOW_WORD: string;
export declare function IMAGE_ORDINAL64(Ordinal: string): string;
export declare function IMAGE_SNAP_BY_ORDINAL64(Ordinal: string): boolean;
export declare class IMAGE_DATA_DIRECTORY extends NativeClass {
    VirtualAddress: DWORD;
    Size: DWORD;
}
export declare class IMAGE_DOS_HEADER extends NativeClass {
    e_magic: WORD;
    e_cblp: WORD;
    e_cp: WORD;
    e_crlc: WORD;
    e_cparhdr: WORD;
    e_minalloc: WORD;
    e_maxalloc: WORD;
    e_ss: WORD;
    e_sp: WORD;
    e_csum: WORD;
    e_ip: WORD;
    e_cs: WORD;
    e_lfarlc: WORD;
    e_ovno: WORD;
    e_res: NativeArray<WORD>;
    e_oemid: WORD;
    e_oeminfo: WORD;
    e_res2: NativeArray<WORD>;
    e_lfanew: LONG;
}
export declare class IMAGE_FILE_HEADER extends NativeClass {
    Machine: WORD;
    NumberOfSections: WORD;
    TimeDateStamp: DWORD;
    PointerToSymbolTable: DWORD;
    NumberOfSymbols: DWORD;
    SizeOfOptionalHeader: WORD;
    Characteristics: WORD;
}
export declare class IMAGE_OPTIONAL_HEADER64 extends NativeClass {
    Magic: WORD;
    MajorLinkerVersion: BYTE;
    MinorLinkerVersion: BYTE;
    SizeOfCode: DWORD;
    SizeOfInitializedData: DWORD;
    SizeOfUninitializedData: DWORD;
    AddressOfEntryPoint: DWORD;
    BaseOfCode: DWORD;
    ImageBase: ULONGLONG;
    SectionAlignment: DWORD;
    FileAlignment: DWORD;
    MajorOperatingSystemVersion: WORD;
    MinorOperatingSystemVersion: WORD;
    MajorImageVersion: WORD;
    MinorImageVersion: WORD;
    MajorSubsystemVersion: WORD;
    MinorSubsystemVersion: WORD;
    Win32VersionValue: DWORD;
    SizeOfImage: DWORD;
    SizeOfHeaders: DWORD;
    CheckSum: DWORD;
    Subsystem: WORD;
    DllCharacteristics: WORD;
    SizeOfStackReserve: ULONGLONG;
    SizeOfStackCommit: ULONGLONG;
    SizeOfHeapReserve: ULONGLONG;
    SizeOfHeapCommit: ULONGLONG;
    LoaderFlags: DWORD;
    NumberOfRvaAndSizes: DWORD;
    DataDirectory: NativeArray<IMAGE_DATA_DIRECTORY>;
}
export declare class IMAGE_NT_HEADERS64 extends NativeClass {
    Signature: DWORD;
    FileHeader: IMAGE_FILE_HEADER;
    OptionalHeader: IMAGE_OPTIONAL_HEADER64;
}
export declare class IMAGE_DEBUG_DIRECTORY extends NativeClass {
    Characteristics: DWORD;
    TimeDateStamp: DWORD;
    MajorVersion: WORD;
    MinorVersion: WORD;
    Type: DWORD;
    SizeOfData: DWORD;
    AddressOfRawData: DWORD;
    PointerToRawData: DWORD;
}
export declare class IMAGE_IMPORT_DESCRIPTOR extends NativeClass {
    Characteristics: DWORD;
    OriginalFirstThunk: DWORD;
    TimeDateStamp: DWORD;
    ForwarderChain: DWORD;
    Name: DWORD;
    FirstThunk: DWORD;
}
declare class IMAGE_THUNK_DATA64_union extends NativeClass {
    ForwarderString: ULONGLONG;
    Function: ULONGLONG;
    Ordinal: ULONGLONG;
    AddressOfData: ULONGLONG;
}
export declare class IMAGE_THUNK_DATA64 extends NativeClass {
    u1: IMAGE_THUNK_DATA64_union;
}
declare class IMAGE_SECTION_HEADER_Misc extends NativeClass {
    PhysicalAddress: DWORD;
    VirtualSize: DWORD;
}
export declare class IMAGE_SECTION_HEADER extends NativeClass {
    Name: NativeArray<BYTE>;
    Misc: IMAGE_SECTION_HEADER_Misc;
    VirtualAddress: DWORD;
    SizeOfRawData: DWORD;
    PointerToRawData: DWORD;
    PointerToRelocations: DWORD;
    PointerToLinenumbers: DWORD;
    NumberOfRelocations: WORD;
    NumberOfLinenumbers: WORD;
    Characteristics: DWORD;
}
export declare class EXCEPTION_RECORD extends NativeClass {
    ExceptionCode: DWORD;
    ExceptionFlags: DWORD;
    ExceptionRecord: VoidPointer;
    ExceptionAddress: VoidPointer;
    NumberParameters: DWORD;
    dummy: DWORD;
    ExceptionInformation: NativeArray<ULONG_PTR>;
}
export declare class EXCEPTION_POINTERS extends NativeClass {
    ExceptionRecord: EXCEPTION_RECORD;
    ContextRecord: VoidPointer;
}
export declare class FILETIME extends NativeClass {
    dwLowDateTime: DWORD;
    dwHighDateTime: DWORD;
}
export declare function IMAGE_FIRST_SECTION(ntheader: IMAGE_NT_HEADERS64): IMAGE_SECTION_HEADER;
export declare const EXCEPTION_BREAKPOINT: number;
export declare const EXCEPTION_ACCESS_VIOLATION: number;
export declare const STATUS_INVALID_PARAMETER: number;
export declare const EXCEPTION_NONCONTINUABLE_EXCEPTION: number;
export declare const FORMAT_MESSAGE_ALLOCATE_BUFFER = 256;
export declare const FORMAT_MESSAGE_IGNORE_INSERTS = 512;
export declare const FORMAT_MESSAGE_FROM_STRING = 1024;
export declare const FORMAT_MESSAGE_FROM_HMODULE = 2048;
export declare const FORMAT_MESSAGE_FROM_SYSTEM = 4096;
export declare const FORMAT_MESSAGE_ARGUMENT_ARRAY = 8192;
export declare const FORMAT_MESSAGE_MAX_WIDTH_MASK = 255;
export declare function MAKELANGID(p: number, s: number): number;
export declare function PRIMARYLANGID(lgid: number): number;
export declare function SUBLANGID(lgid: number): number;
export declare const LANG_NEUTRAL = 0;
export declare const LANG_INVARIANT = 127;
export declare const LANG_AFRIKAANS = 54;
export declare const LANG_ALBANIAN = 28;
export declare const LANG_ALSATIAN = 132;
export declare const LANG_AMHARIC = 94;
export declare const LANG_ARABIC = 1;
export declare const LANG_ARMENIAN = 43;
export declare const LANG_ASSAMESE = 77;
export declare const LANG_AZERI = 44;
export declare const LANG_AZERBAIJANI = 44;
export declare const LANG_BANGLA = 69;
export declare const LANG_BASHKIR = 109;
export declare const LANG_BASQUE = 45;
export declare const LANG_BELARUSIAN = 35;
export declare const LANG_BENGALI = 69;
export declare const LANG_BRETON = 126;
export declare const LANG_BOSNIAN = 26;
export declare const LANG_BOSNIAN_NEUTRAL = 30746;
export declare const LANG_BULGARIAN = 2;
export declare const LANG_CATALAN = 3;
export declare const LANG_CENTRAL_KURDISH = 146;
export declare const LANG_CHEROKEE = 92;
export declare const LANG_CHINESE = 4;
export declare const LANG_CHINESE_SIMPLIFIED = 4;
export declare const LANG_CHINESE_TRADITIONAL = 31748;
export declare const LANG_CORSICAN = 131;
export declare const LANG_CROATIAN = 26;
export declare const LANG_CZECH = 5;
export declare const LANG_DANISH = 6;
export declare const LANG_DARI = 140;
export declare const LANG_DIVEHI = 101;
export declare const LANG_DUTCH = 19;
export declare const LANG_ENGLISH = 9;
export declare const LANG_ESTONIAN = 37;
export declare const LANG_FAEROESE = 56;
export declare const LANG_FARSI = 41;
export declare const LANG_FILIPINO = 100;
export declare const LANG_FINNISH = 11;
export declare const LANG_FRENCH = 12;
export declare const LANG_FRISIAN = 98;
export declare const LANG_FULAH = 103;
export declare const LANG_GALICIAN = 86;
export declare const LANG_GEORGIAN = 55;
export declare const LANG_GERMAN = 7;
export declare const LANG_GREEK = 8;
export declare const LANG_GREENLANDIC = 111;
export declare const LANG_GUJARATI = 71;
export declare const LANG_HAUSA = 104;
export declare const LANG_HAWAIIAN = 117;
export declare const LANG_HEBREW = 13;
export declare const LANG_HINDI = 57;
export declare const LANG_HUNGARIAN = 14;
export declare const LANG_ICELANDIC = 15;
export declare const LANG_IGBO = 112;
export declare const LANG_INDONESIAN = 33;
export declare const LANG_INUKTITUT = 93;
export declare const LANG_IRISH = 60;
export declare const LANG_ITALIAN = 16;
export declare const LANG_JAPANESE = 17;
export declare const LANG_KANNADA = 75;
export declare const LANG_KASHMIRI = 96;
export declare const LANG_KAZAK = 63;
export declare const LANG_KHMER = 83;
export declare const LANG_KICHE = 134;
export declare const LANG_KINYARWANDA = 135;
export declare const LANG_KONKANI = 87;
export declare const LANG_KOREAN = 18;
export declare const LANG_KYRGYZ = 64;
export declare const LANG_LAO = 84;
export declare const LANG_LATVIAN = 38;
export declare const LANG_LITHUANIAN = 39;
export declare const LANG_LOWER_SORBIAN = 46;
export declare const LANG_LUXEMBOURGISH = 110;
export declare const LANG_MACEDONIAN = 47;
export declare const LANG_MALAY = 62;
export declare const LANG_MALAYALAM = 76;
export declare const LANG_MALTESE = 58;
export declare const LANG_MANIPURI = 88;
export declare const LANG_MAORI = 129;
export declare const LANG_MAPUDUNGUN = 122;
export declare const LANG_MARATHI = 78;
export declare const LANG_MOHAWK = 124;
export declare const LANG_MONGOLIAN = 80;
export declare const LANG_NEPALI = 97;
export declare const LANG_NORWEGIAN = 20;
export declare const LANG_OCCITAN = 130;
export declare const LANG_ODIA = 72;
export declare const LANG_ORIYA = 72;
export declare const LANG_PASHTO = 99;
export declare const LANG_PERSIAN = 41;
export declare const LANG_POLISH = 21;
export declare const LANG_PORTUGUESE = 22;
export declare const LANG_PULAR = 103;
export declare const LANG_PUNJABI = 70;
export declare const LANG_QUECHUA = 107;
export declare const LANG_ROMANIAN = 24;
export declare const LANG_ROMANSH = 23;
export declare const LANG_RUSSIAN = 25;
export declare const LANG_SAKHA = 133;
export declare const LANG_SAMI = 59;
export declare const LANG_SANSKRIT = 79;
export declare const LANG_SCOTTISH_GAELIC = 145;
export declare const LANG_SERBIAN = 26;
export declare const LANG_SERBIAN_NEUTRAL = 31770;
export declare const LANG_SINDHI = 89;
export declare const LANG_SINHALESE = 91;
export declare const LANG_SLOVAK = 27;
export declare const LANG_SLOVENIAN = 36;
export declare const LANG_SOTHO = 108;
export declare const LANG_SPANISH = 10;
export declare const LANG_SWAHILI = 65;
export declare const LANG_SWEDISH = 29;
export declare const LANG_SYRIAC = 90;
export declare const LANG_TAJIK = 40;
export declare const LANG_TAMAZIGHT = 95;
export declare const LANG_TAMIL = 73;
export declare const LANG_TATAR = 68;
export declare const LANG_TELUGU = 74;
export declare const LANG_THAI = 30;
export declare const LANG_TIBETAN = 81;
export declare const LANG_TIGRIGNA = 115;
export declare const LANG_TIGRINYA = 115;
export declare const LANG_TSWANA = 50;
export declare const LANG_TURKISH = 31;
export declare const LANG_TURKMEN = 66;
export declare const LANG_UIGHUR = 128;
export declare const LANG_UKRAINIAN = 34;
export declare const LANG_UPPER_SORBIAN = 46;
export declare const LANG_URDU = 32;
export declare const LANG_UZBEK = 67;
export declare const LANG_VALENCIAN = 3;
export declare const LANG_VIETNAMESE = 42;
export declare const LANG_WELSH = 82;
export declare const LANG_WOLOF = 136;
export declare const LANG_XHOSA = 52;
export declare const LANG_YAKUT = 133;
export declare const LANG_YI = 120;
export declare const LANG_YORUBA = 106;
export declare const LANG_ZULU = 53;
export declare const SUBLANG_NEUTRAL = 0;
export declare const SUBLANG_DEFAULT = 1;
export declare const SUBLANG_SYS_DEFAULT = 2;
export declare const SUBLANG_CUSTOM_DEFAULT = 3;
export declare const SUBLANG_CUSTOM_UNSPECIFIED = 4;
export declare const SUBLANG_UI_CUSTOM_DEFAULT = 5;
export declare const SUBLANG_AFRIKAANS_SOUTH_AFRICA = 1;
export declare const SUBLANG_ALBANIAN_ALBANIA = 1;
export declare const SUBLANG_ALSATIAN_FRANCE = 1;
export declare const SUBLANG_AMHARIC_ETHIOPIA = 1;
export declare const SUBLANG_ARABIC_SAUDI_ARABIA = 1;
export declare const SUBLANG_ARABIC_IRAQ = 2;
export declare const SUBLANG_ARABIC_EGYPT = 3;
export declare const SUBLANG_ARABIC_LIBYA = 4;
export declare const SUBLANG_ARABIC_ALGERIA = 5;
export declare const SUBLANG_ARABIC_MOROCCO = 6;
export declare const SUBLANG_ARABIC_TUNISIA = 7;
export declare const SUBLANG_ARABIC_OMAN = 8;
export declare const SUBLANG_ARABIC_YEMEN = 9;
export declare const SUBLANG_ARABIC_SYRIA = 10;
export declare const SUBLANG_ARABIC_JORDAN = 11;
export declare const SUBLANG_ARABIC_LEBANON = 12;
export declare const SUBLANG_ARABIC_KUWAIT = 13;
export declare const SUBLANG_ARABIC_UAE = 14;
export declare const SUBLANG_ARABIC_BAHRAIN = 15;
export declare const SUBLANG_ARABIC_QATAR = 16;
export declare const SUBLANG_ARMENIAN_ARMENIA = 1;
export declare const SUBLANG_ASSAMESE_INDIA = 1;
export declare const SUBLANG_AZERI_LATIN = 1;
export declare const SUBLANG_AZERI_CYRILLIC = 2;
export declare const SUBLANG_AZERBAIJANI_AZERBAIJAN_LATIN = 1;
export declare const SUBLANG_AZERBAIJANI_AZERBAIJAN_CYRILLIC = 2;
export declare const SUBLANG_BANGLA_INDIA = 1;
export declare const SUBLANG_BANGLA_BANGLADESH = 2;
export declare const SUBLANG_BASHKIR_RUSSIA = 1;
export declare const SUBLANG_BASQUE_BASQUE = 1;
export declare const SUBLANG_BELARUSIAN_BELARUS = 1;
export declare const SUBLANG_BENGALI_INDIA = 1;
export declare const SUBLANG_BENGALI_BANGLADESH = 2;
export declare const SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_LATIN = 5;
export declare const SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_CYRILLIC = 8;
export declare const SUBLANG_BRETON_FRANCE = 1;
export declare const SUBLANG_BULGARIAN_BULGARIA = 1;
export declare const SUBLANG_CATALAN_CATALAN = 1;
export declare const SUBLANG_CENTRAL_KURDISH_IRAQ = 1;
export declare const SUBLANG_CHEROKEE_CHEROKEE = 1;
export declare const SUBLANG_CHINESE_TRADITIONAL = 1;
export declare const SUBLANG_CHINESE_SIMPLIFIED = 2;
export declare const SUBLANG_CHINESE_HONGKONG = 3;
export declare const SUBLANG_CHINESE_SINGAPORE = 4;
export declare const SUBLANG_CHINESE_MACAU = 5;
export declare const SUBLANG_CORSICAN_FRANCE = 1;
export declare const SUBLANG_CZECH_CZECH_REPUBLIC = 1;
export declare const SUBLANG_CROATIAN_CROATIA = 1;
export declare const SUBLANG_CROATIAN_BOSNIA_HERZEGOVINA_LATIN = 4;
export declare const SUBLANG_DANISH_DENMARK = 1;
export declare const SUBLANG_DARI_AFGHANISTAN = 1;
export declare const SUBLANG_DIVEHI_MALDIVES = 1;
export declare const SUBLANG_DUTCH = 1;
export declare const SUBLANG_DUTCH_BELGIAN = 2;
export declare const SUBLANG_ENGLISH_US = 1;
export declare const SUBLANG_ENGLISH_UK = 2;
export declare const SUBLANG_ENGLISH_AUS = 3;
export declare const SUBLANG_ENGLISH_CAN = 4;
export declare const SUBLANG_ENGLISH_NZ = 5;
export declare const SUBLANG_ENGLISH_EIRE = 6;
export declare const SUBLANG_ENGLISH_SOUTH_AFRICA = 7;
export declare const SUBLANG_ENGLISH_JAMAICA = 8;
export declare const SUBLANG_ENGLISH_CARIBBEAN = 9;
export declare const SUBLANG_ENGLISH_BELIZE = 10;
export declare const SUBLANG_ENGLISH_TRINIDAD = 11;
export declare const SUBLANG_ENGLISH_ZIMBABWE = 12;
export declare const SUBLANG_ENGLISH_PHILIPPINES = 13;
export declare const SUBLANG_ENGLISH_INDIA = 16;
export declare const SUBLANG_ENGLISH_MALAYSIA = 17;
export declare const SUBLANG_ENGLISH_SINGAPORE = 18;
export declare const SUBLANG_ESTONIAN_ESTONIA = 1;
export declare const SUBLANG_FAEROESE_FAROE_ISLANDS = 1;
export declare const SUBLANG_FILIPINO_PHILIPPINES = 1;
export declare const SUBLANG_FINNISH_FINLAND = 1;
export declare const SUBLANG_FRENCH = 1;
export declare const SUBLANG_FRENCH_BELGIAN = 2;
export declare const SUBLANG_FRENCH_CANADIAN = 3;
export declare const SUBLANG_FRENCH_SWISS = 4;
export declare const SUBLANG_FRENCH_LUXEMBOURG = 5;
export declare const SUBLANG_FRENCH_MONACO = 6;
export declare const SUBLANG_FRISIAN_NETHERLANDS = 1;
export declare const SUBLANG_FULAH_SENEGAL = 2;
export declare const SUBLANG_GALICIAN_GALICIAN = 1;
export declare const SUBLANG_GEORGIAN_GEORGIA = 1;
export declare const SUBLANG_GERMAN = 1;
export declare const SUBLANG_GERMAN_SWISS = 2;
export declare const SUBLANG_GERMAN_AUSTRIAN = 3;
export declare const SUBLANG_GERMAN_LUXEMBOURG = 4;
export declare const SUBLANG_GERMAN_LIECHTENSTEIN = 5;
export declare const SUBLANG_GREEK_GREECE = 1;
export declare const SUBLANG_GREENLANDIC_GREENLAND = 1;
export declare const SUBLANG_GUJARATI_INDIA = 1;
export declare const SUBLANG_HAUSA_NIGERIA_LATIN = 1;
export declare const SUBLANG_HAWAIIAN_US = 1;
export declare const SUBLANG_HEBREW_ISRAEL = 1;
export declare const SUBLANG_HINDI_INDIA = 1;
export declare const SUBLANG_HUNGARIAN_HUNGARY = 1;
export declare const SUBLANG_ICELANDIC_ICELAND = 1;
export declare const SUBLANG_IGBO_NIGERIA = 1;
export declare const SUBLANG_INDONESIAN_INDONESIA = 1;
export declare const SUBLANG_INUKTITUT_CANADA = 1;
export declare const SUBLANG_INUKTITUT_CANADA_LATIN = 2;
export declare const SUBLANG_IRISH_IRELAND = 2;
export declare const SUBLANG_ITALIAN = 1;
export declare const SUBLANG_ITALIAN_SWISS = 2;
export declare const SUBLANG_JAPANESE_JAPAN = 1;
export declare const SUBLANG_KANNADA_INDIA = 1;
export declare const SUBLANG_KASHMIRI_SASIA = 2;
export declare const SUBLANG_KASHMIRI_INDIA = 2;
export declare const SUBLANG_KAZAK_KAZAKHSTAN = 1;
export declare const SUBLANG_KHMER_CAMBODIA = 1;
export declare const SUBLANG_KICHE_GUATEMALA = 1;
export declare const SUBLANG_KINYARWANDA_RWANDA = 1;
export declare const SUBLANG_KONKANI_INDIA = 1;
export declare const SUBLANG_KOREAN = 1;
export declare const SUBLANG_KYRGYZ_KYRGYZSTAN = 1;
export declare const SUBLANG_LAO_LAO = 1;
export declare const SUBLANG_LATVIAN_LATVIA = 1;
export declare const SUBLANG_LITHUANIAN = 1;
export declare const SUBLANG_LOWER_SORBIAN_GERMANY = 2;
export declare const SUBLANG_LUXEMBOURGISH_LUXEMBOURG = 1;
export declare const SUBLANG_MACEDONIAN_MACEDONIA = 1;
export declare const SUBLANG_MALAY_MALAYSIA = 1;
export declare const SUBLANG_MALAY_BRUNEI_DARUSSALAM = 2;
export declare const SUBLANG_MALAYALAM_INDIA = 1;
export declare const SUBLANG_MALTESE_MALTA = 1;
export declare const SUBLANG_MAORI_NEW_ZEALAND = 1;
export declare const SUBLANG_MAPUDUNGUN_CHILE = 1;
export declare const SUBLANG_MARATHI_INDIA = 1;
export declare const SUBLANG_MOHAWK_MOHAWK = 1;
export declare const SUBLANG_MONGOLIAN_CYRILLIC_MONGOLIA = 1;
export declare const SUBLANG_MONGOLIAN_PRC = 2;
export declare const SUBLANG_NEPALI_INDIA = 2;
export declare const SUBLANG_NEPALI_NEPAL = 1;
export declare const SUBLANG_NORWEGIAN_BOKMAL = 1;
export declare const SUBLANG_NORWEGIAN_NYNORSK = 2;
export declare const SUBLANG_OCCITAN_FRANCE = 1;
export declare const SUBLANG_ODIA_INDIA = 1;
export declare const SUBLANG_ORIYA_INDIA = 1;
export declare const SUBLANG_PASHTO_AFGHANISTAN = 1;
export declare const SUBLANG_PERSIAN_IRAN = 1;
export declare const SUBLANG_POLISH_POLAND = 1;
export declare const SUBLANG_PORTUGUESE = 2;
export declare const SUBLANG_PORTUGUESE_BRAZILIAN = 1;
export declare const SUBLANG_PULAR_SENEGAL = 2;
export declare const SUBLANG_PUNJABI_INDIA = 1;
export declare const SUBLANG_PUNJABI_PAKISTAN = 2;
export declare const SUBLANG_QUECHUA_BOLIVIA = 1;
export declare const SUBLANG_QUECHUA_ECUADOR = 2;
export declare const SUBLANG_QUECHUA_PERU = 3;
export declare const SUBLANG_ROMANIAN_ROMANIA = 1;
export declare const SUBLANG_ROMANSH_SWITZERLAND = 1;
export declare const SUBLANG_RUSSIAN_RUSSIA = 1;
export declare const SUBLANG_SAKHA_RUSSIA = 1;
export declare const SUBLANG_SAMI_NORTHERN_NORWAY = 1;
export declare const SUBLANG_SAMI_NORTHERN_SWEDEN = 2;
export declare const SUBLANG_SAMI_NORTHERN_FINLAND = 3;
export declare const SUBLANG_SAMI_LULE_NORWAY = 4;
export declare const SUBLANG_SAMI_LULE_SWEDEN = 5;
export declare const SUBLANG_SAMI_SOUTHERN_NORWAY = 6;
export declare const SUBLANG_SAMI_SOUTHERN_SWEDEN = 7;
export declare const SUBLANG_SAMI_SKOLT_FINLAND = 8;
export declare const SUBLANG_SAMI_INARI_FINLAND = 9;
export declare const SUBLANG_SANSKRIT_INDIA = 1;
export declare const SUBLANG_SCOTTISH_GAELIC = 1;
export declare const SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_LATIN = 6;
export declare const SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_CYRILLIC = 7;
export declare const SUBLANG_SERBIAN_MONTENEGRO_LATIN = 11;
export declare const SUBLANG_SERBIAN_MONTENEGRO_CYRILLIC = 12;
export declare const SUBLANG_SERBIAN_SERBIA_LATIN = 9;
export declare const SUBLANG_SERBIAN_SERBIA_CYRILLIC = 10;
export declare const SUBLANG_SERBIAN_CROATIA = 1;
export declare const SUBLANG_SERBIAN_LATIN = 2;
export declare const SUBLANG_SERBIAN_CYRILLIC = 3;
export declare const SUBLANG_SINDHI_INDIA = 1;
export declare const SUBLANG_SINDHI_PAKISTAN = 2;
export declare const SUBLANG_SINDHI_AFGHANISTAN = 2;
export declare const SUBLANG_SINHALESE_SRI_LANKA = 1;
export declare const SUBLANG_SOTHO_NORTHERN_SOUTH_AFRICA = 1;
export declare const SUBLANG_SLOVAK_SLOVAKIA = 1;
export declare const SUBLANG_SLOVENIAN_SLOVENIA = 1;
export declare const SUBLANG_SPANISH = 1;
export declare const SUBLANG_SPANISH_MEXICAN = 2;
export declare const SUBLANG_SPANISH_MODERN = 3;
export declare const SUBLANG_SPANISH_GUATEMALA = 4;
export declare const SUBLANG_SPANISH_COSTA_RICA = 5;
export declare const SUBLANG_SPANISH_PANAMA = 6;
export declare const SUBLANG_SPANISH_DOMINICAN_REPUBLIC = 7;
export declare const SUBLANG_SPANISH_VENEZUELA = 8;
export declare const SUBLANG_SPANISH_COLOMBIA = 9;
export declare const SUBLANG_SPANISH_PERU = 10;
export declare const SUBLANG_SPANISH_ARGENTINA = 11;
export declare const SUBLANG_SPANISH_ECUADOR = 12;
export declare const SUBLANG_SPANISH_CHILE = 13;
export declare const SUBLANG_SPANISH_URUGUAY = 14;
export declare const SUBLANG_SPANISH_PARAGUAY = 15;
export declare const SUBLANG_SPANISH_BOLIVIA = 16;
export declare const SUBLANG_SPANISH_EL_SALVADOR = 17;
export declare const SUBLANG_SPANISH_HONDURAS = 18;
export declare const SUBLANG_SPANISH_NICARAGUA = 19;
export declare const SUBLANG_SPANISH_PUERTO_RICO = 20;
export declare const SUBLANG_SPANISH_US = 21;
export declare const SUBLANG_SWAHILI_KENYA = 1;
export declare const SUBLANG_SWEDISH = 1;
export declare const SUBLANG_SWEDISH_FINLAND = 2;
export declare const SUBLANG_SYRIAC_SYRIA = 1;
export declare const SUBLANG_TAJIK_TAJIKISTAN = 1;
export declare const SUBLANG_TAMAZIGHT_ALGERIA_LATIN = 2;
export declare const SUBLANG_TAMAZIGHT_MOROCCO_TIFINAGH = 4;
export declare const SUBLANG_TAMIL_INDIA = 1;
export declare const SUBLANG_TAMIL_SRI_LANKA = 2;
export declare const SUBLANG_TATAR_RUSSIA = 1;
export declare const SUBLANG_TELUGU_INDIA = 1;
export declare const SUBLANG_THAI_THAILAND = 1;
export declare const SUBLANG_TIBETAN_PRC = 1;
export declare const SUBLANG_TIGRIGNA_ERITREA = 2;
export declare const SUBLANG_TIGRINYA_ERITREA = 2;
export declare const SUBLANG_TIGRINYA_ETHIOPIA = 1;
export declare const SUBLANG_TSWANA_BOTSWANA = 2;
export declare const SUBLANG_TSWANA_SOUTH_AFRICA = 1;
export declare const SUBLANG_TURKISH_TURKEY = 1;
export declare const SUBLANG_TURKMEN_TURKMENISTAN = 1;
export declare const SUBLANG_UIGHUR_PRC = 1;
export declare const SUBLANG_UKRAINIAN_UKRAINE = 1;
export declare const SUBLANG_UPPER_SORBIAN_GERMANY = 1;
export declare const SUBLANG_URDU_PAKISTAN = 1;
export declare const SUBLANG_URDU_INDIA = 2;
export declare const SUBLANG_UZBEK_LATIN = 1;
export declare const SUBLANG_UZBEK_CYRILLIC = 2;
export declare const SUBLANG_VALENCIAN_VALENCIA = 2;
export declare const SUBLANG_VIETNAMESE_VIETNAM = 1;
export declare const SUBLANG_WELSH_UNITED_KINGDOM = 1;
export declare const SUBLANG_WOLOF_SENEGAL = 1;
export declare const SUBLANG_XHOSA_SOUTH_AFRICA = 1;
export declare const SUBLANG_YAKUT_RUSSIA = 1;
export declare const SUBLANG_YI_PRC = 1;
export declare const SUBLANG_YORUBA_NIGERIA = 1;
export declare const SUBLANG_ZULU_SOUTH_AFRICA = 1;
export declare const ERROR_MOD_NOT_FOUND = 126;
export {};
